### ISSUE TITLE
Consider migrating from Joda Time to java.time

### ISSUE THREAD

**Issue by ggrossman** [zendesk/scala-flow#12]
From http://www.joda.org/joda-time/:

>The standard date and time classes prior to Java SE 8 are poor. By tackling this problem head-on, Joda-Time became the de facto standard date and time library for Java prior to Java SE 8. Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project.

@dasch @ciaranarcher

**Comment by dasch** [comment]
We know, but the Dataflow SDK itself uses joda, so there's no way around it.

**Comment by bcasey-zd** [comment]
@ggrossman That's a reasonable suggestion and something we considered. It was surprising nearly 3 years after Java 8 has been released to find a new library still using Joda!

Unfortunately Joda is embedded deeply into the Dataflow SDK (and also in it's successor Apache Beam <sigh>) which makes it confusing and difficult to use 2 date/time APIs

-

**Comment by ggrossman** [comment]
@bcasey-zd Understood; feel free to close this or keep it around for tracking if it's helpful

**Comment by dasch** [comment]
Closing it for now – we'll revisit it if Dataflow switches to `java.time`.
